# Generated by Django 3.2.5 on 2023-02-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.CharField(default=0, max_length=10)),
            ],
        ),
    ]
