# Generated by Django 3.2.5 on 2023-02-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0003_alter_settings_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='interest_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='settings',
            name='interest_rate',
            field=models.IntegerField(default=0),
        ),
    ]
