# Generated by Django 3.2.5 on 2023-02-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0002_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='interest_rate',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
