# Generated by Django 3.2.5 on 2023-08-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0004_auto_20230227_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sold_by',
            field=models.CharField(default='Unit', max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='units',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='settings',
            name='interest_rate',
            field=models.IntegerField(default=9),
        ),
    ]
